# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'x:\Python\_Project\CryptoKing\ui\Forms\MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(880, 621)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.w_head = QtWidgets.QFrame(self.widget)
        self.w_head.setMinimumSize(QtCore.QSize(0, 80))
        self.w_head.setStyleSheet("background-color: #66afe9;")
        self.w_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.w_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.w_head.setObjectName("w_head")
        self.btn_close = QtWidgets.QPushButton(self.w_head)
        self.btn_close.setGeometry(QtCore.QRect(856, 10, 16, 16))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_min = QtWidgets.QPushButton(self.w_head)
        self.btn_min.setGeometry(QtCore.QRect(830, 10, 16, 16))
        self.btn_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_min.setText("")
        self.btn_min.setObjectName("btn_min")
        self.lbl_app_name = QtWidgets.QLabel(self.w_head)
        self.lbl_app_name.setGeometry(QtCore.QRect(12, 10, 181, 41))
        self.lbl_app_name.setStyleSheet("font: 24pt \"微软雅黑\";\n"
"color: #fff;")
        self.lbl_app_name.setObjectName("lbl_app_name")
        self.verticalLayout_3.addWidget(self.w_head)
        self.w_main = QtWidgets.QWidget(self.widget)
        self.w_main.setStyleSheet("")
        self.w_main.setObjectName("w_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.w_main)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgettt = QtWidgets.QWidget(self.w_main)
        self.widgettt.setMinimumSize(QtCore.QSize(200, 0))
        self.widgettt.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widgettt.setStyleSheet("border-radius: 100px;")
        self.widgettt.setObjectName("widgettt")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgettt)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.widgettt)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("*{\n"
"    color: #000;\n"
"}\n"
"\n"
"QToolBox{\n"
"/*background-color: rgb(80, 80, 80);*//*背景色-空隙颜色*/\n"
"/*border:1px solid rgb(128, 128, 128);*/\n"
"}\n"
"QToolBox QWidget{/*tab页*/\n"
"/*background: #fff;*/\n"
"}\n"
"QToolBox>QAbstractButton{/*标题栏*/\n"
"min-height:40px;\n"
"font: 13pt \"微软雅黑\";\n"
"padding-left:10px;\n"
"}\n"
"QToolBox::tab{\n"
"background-color:#66afe9;/*rgb(40, 40, 40);*/\n"
"}\n"
"QToolBox::tab:hover{\n"
"color:black;\n"
"background-color: rgb(255, 170, 0);\n"
"}\n"
"QToolBox::tab:selected{\n"
"color:rgb(255, 170, 0);\n"
"background:#1976d2;\n"
"}\n"
"QToolBox::tab:selected:hover{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 4px;\n"
"    background: #66afe9;\n"
"    border: none;\n"
"    color: #FFFFFF;\n"
"    height:35px;\n"
"    min-height:35px;\n"
"    text-align: center;\n"
"    font: 11pt \"微软雅黑\";\n"
"    margin: 2px;\n"
"    vertical-align: middle;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"    right: 0;\n"
"    background-color: #1976d2;\n"
"}\n"
"\n"
"")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.tab = QtWidgets.QWidget()
        self.tab.setGeometry(QtCore.QRect(0, 0, 200, 421))
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_example = QtWidgets.QPushButton(self.tab)
        self.btn_example.setMinimumSize(QtCore.QSize(0, 39))
        self.btn_example.setStyleSheet("")
        self.btn_example.setObjectName("btn_example")
        self.verticalLayout_7.addWidget(self.btn_example)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.toolBox.addItem(self.tab, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 200, 421))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_case_conversion = QtWidgets.QPushButton(self.page_2)
        self.btn_case_conversion.setMinimumSize(QtCore.QSize(0, 39))
        self.btn_case_conversion.setStyleSheet("")
        self.btn_case_conversion.setObjectName("btn_case_conversion")
        self.verticalLayout_4.addWidget(self.btn_case_conversion)
        self.btn_base_encode = QtWidgets.QPushButton(self.page_2)
        self.btn_base_encode.setMinimumSize(QtCore.QSize(0, 39))
        self.btn_base_encode.setStyleSheet("")
        self.btn_base_encode.setObjectName("btn_base_encode")
        self.verticalLayout_4.addWidget(self.btn_base_encode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 200, 421))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_2.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout.addWidget(self.widgettt)
        self.stackedWidget = QtWidgets.QStackedWidget(self.w_main)
        self.stackedWidget.setMinimumSize(QtCore.QSize(640, 480))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.HelloWidget = QtWidgets.QWidget()
        self.HelloWidget.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.HelloWidget.setObjectName("HelloWidget")
        self.stackedWidget.addWidget(self.HelloWidget)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.w_main)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.toolBox.layout().setSpacing(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CryptoKing"))
        self.lbl_app_name.setText(_translate("Form", "CryptoKing"))
        self.btn_example.setText(_translate("Form", "编码解码"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab), _translate("Form", "Example"))
        self.btn_case_conversion.setText(_translate("Form", "英文大小写转换"))
        self.btn_base_encode.setText(_translate("Form", "Base编码"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "编码转换"))
        self.pushButton_4.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "其他"))
