# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 610)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setMinimumSize(QtCore.QSize(640, 480))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.HelloWidget = QtWidgets.QWidget()
        self.HelloWidget.setObjectName("HelloWidget")
        self.label = QtWidgets.QLabel(self.HelloWidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 551, 191))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.HelloWidget)
        self.gridLayout.addWidget(self.stackedWidget, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 130))
        self.frame.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_case_conversion = QtWidgets.QPushButton(self.widget)
        self.btn_case_conversion.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_case_conversion.setObjectName("btn_case_conversion")
        self.verticalLayout.addWidget(self.btn_case_conversion)
        self.btn_base_encode = QtWidgets.QPushButton(self.widget)
        self.btn_base_encode.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_base_encode.setObjectName("btn_base_encode")
        self.verticalLayout.addWidget(self.btn_base_encode)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CryptoKing"))
        self.label.setText(_translate("Form", "hello"))
        self.btn_case_conversion.setText(_translate("Form", "英文大小写转换"))
        self.btn_base_encode.setText(_translate("Form", "Base编码"))
