# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BaseWidget(object):
    def setupUi(self, BaseWidget):
        BaseWidget.setObjectName("BaseWidget")
        BaseWidget.resize(619, 395)
        BaseWidget.setMinimumSize(QtCore.QSize(90, 40))
        self.txt_left = QtWidgets.QPlainTextEdit(BaseWidget)
        self.txt_left.setGeometry(QtCore.QRect(10, 20, 291, 201))
        self.txt_left.setPlainText("")
        self.txt_left.setObjectName("txt_left")
        self.txt_right = QtWidgets.QPlainTextEdit(BaseWidget)
        self.txt_right.setGeometry(QtCore.QRect(310, 20, 301, 201))
        self.txt_right.setReadOnly(True)
        self.txt_right.setObjectName("txt_right")
        self.btn_encode = QtWidgets.QPushButton(BaseWidget)
        self.btn_encode.setGeometry(QtCore.QRect(10, 230, 90, 40))
        self.btn_encode.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_encode.setMaximumSize(QtCore.QSize(90, 40))
        self.btn_encode.setObjectName("btn_encode")
        self.btn_decode = QtWidgets.QPushButton(BaseWidget)
        self.btn_decode.setGeometry(QtCore.QRect(110, 230, 90, 40))
        self.btn_decode.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_decode.setMaximumSize(QtCore.QSize(90, 40))
        self.btn_decode.setObjectName("btn_decode")

        self.retranslateUi(BaseWidget)
        QtCore.QMetaObject.connectSlotsByName(BaseWidget)

    def retranslateUi(self, BaseWidget):
        _translate = QtCore.QCoreApplication.translate
        BaseWidget.setWindowTitle(_translate("BaseWidget", "Form"))
        self.btn_encode.setText(_translate("BaseWidget", "编码"))
        self.btn_decode.setText(_translate("BaseWidget", "解码"))
