# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BaseWidget(object):
    def setupUi(self, BaseWidget):
        BaseWidget.setObjectName("BaseWidget")
        BaseWidget.resize(631, 461)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(BaseWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 90, 301, 201))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(BaseWidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(320, 90, 301, 201))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(BaseWidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 300, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(BaseWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 300, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(BaseWidget)
        QtCore.QMetaObject.connectSlotsByName(BaseWidget)

    def retranslateUi(self, BaseWidget):
        _translate = QtCore.QCoreApplication.translate
        BaseWidget.setWindowTitle(_translate("BaseWidget", "Form"))
        self.pushButton.setText(_translate("BaseWidget", "编码"))
        self.pushButton_2.setText(_translate("BaseWidget", "解码"))
