# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'x:\Python\.Project\CryptoKing\ui\Widgets\encoding\BaseEncode\BaseWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BaseWidget(object):
    def setupUi(self, BaseWidget):
        BaseWidget.setObjectName("BaseWidget")
        BaseWidget.resize(758, 513)
        BaseWidget.setMinimumSize(QtCore.QSize(90, 40))
        self.verticalLayout = QtWidgets.QVBoxLayout(BaseWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(BaseWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_3.setObjectName("widget_3")
        self.combo_method = QtWidgets.QComboBox(self.widget_3)
        self.combo_method.setGeometry(QtCore.QRect(10, 10, 201, 41))
        self.combo_method.setStyleSheet("QComboBox{\n"
"  background: #66afe9;\n"
"  color:#fff;\n"
"  font: 11pt \"微软雅黑\";\n"
"  font-size:14px;\n"
"  padding: 1px 15px 1px 10px;\n"
"  border:1px solid rgba(228,228,228,1);\n"
"  border-radius:5px 5px 0px 0px;\n"
"}\n"
"\n"
"  QComboBox::drop-down {\n"
"      subcontrol-origin: padding;\n"
"      subcontrol-position: top right;\n"
"      width: 15px;\n"
"      border:none;\n"
"  }\n"
"\n"
"QComboBox QAbstractItemView {\n"
"outline: 0px solid gray;\n"
"border: 1px solid #fff;\n"
"color: #000;\n"
"background-color: #fff;\n"
"selection-background-color: #1976d2;\n"
"}\n"
"")
        self.combo_method.setObjectName("combo_method")
        self.combo_method.addItem("")
        self.combo_method.addItem("")
        self.combo_method.addItem("")
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(BaseWidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 280))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_left = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_left.setMinimumSize(QtCore.QSize(0, 250))
        self.txt_left.setMaximumSize(QtCore.QSize(16777215, 250))
        self.txt_left.setStyleSheet("QPlainTextEdit {\n"
"font-size: 14px;\n"
"color: #000;\n"
"font: 11pt \"微软雅黑\";\n"
"background-color: #ffffff;\n"
"border: 1px solid #cccccc;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"border-color: #66afe9;\n"
"outline: 0;\n"
"}")
        self.txt_left.setPlainText("")
        self.txt_left.setObjectName("txt_left")
        self.horizontalLayout.addWidget(self.txt_left)
        self.txt_right = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_right.setMinimumSize(QtCore.QSize(0, 250))
        self.txt_right.setMaximumSize(QtCore.QSize(16777215, 250))
        self.txt_right.setStyleSheet("QPlainTextEdit {\n"
"font-size: 14px;\n"
"color: #000;\n"
"font: 11pt \"微软雅黑\";\n"
"background-color: #ffffff;\n"
"border: 1px solid #cccccc;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"border-color: #66afe9;\n"
"outline: 0;\n"
"}")
        self.txt_right.setReadOnly(True)
        self.txt_right.setObjectName("txt_right")
        self.horizontalLayout.addWidget(self.txt_right)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(BaseWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(1111111, 58))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_encode = QtWidgets.QPushButton(self.widget_2)
        self.btn_encode.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_encode.setMaximumSize(QtCore.QSize(90, 40))
        self.btn_encode.setStyleSheet("QPushButton {\n"
"    border-radius: 4px;\n"
"    background-color: #66afe9;\n"
"    border: none;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"    font: 11pt \"微软雅黑\";\n"
"    margin: 2px;\n"
"    vertical-align: middle;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"    right: 0;\n"
"    background-color: #1976d2;\n"
"}\n"
"")
        self.btn_encode.setObjectName("btn_encode")
        self.horizontalLayout_2.addWidget(self.btn_encode)
        self.btn_decode = QtWidgets.QPushButton(self.widget_2)
        self.btn_decode.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_decode.setMaximumSize(QtCore.QSize(90, 40))
        self.btn_decode.setStyleSheet("QPushButton {\n"
"    border-radius: 4px;\n"
"    background-color: #66afe9;\n"
"    border: none;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"    font: 11pt \"微软雅黑\";\n"
"    margin: 2px;\n"
"    vertical-align: middle;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"    right: 0;\n"
"    background-color: #1976d2;\n"
"}\n"
"")
        self.btn_decode.setObjectName("btn_decode")
        self.horizontalLayout_2.addWidget(self.btn_decode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(BaseWidget)
        QtCore.QMetaObject.connectSlotsByName(BaseWidget)

    def retranslateUi(self, BaseWidget):
        _translate = QtCore.QCoreApplication.translate
        BaseWidget.setWindowTitle(_translate("BaseWidget", "Form"))
        self.combo_method.setItemText(0, _translate("BaseWidget", "Base 64"))
        self.combo_method.setItemText(1, _translate("BaseWidget", "Base 32"))
        self.combo_method.setItemText(2, _translate("BaseWidget", "Base 16"))
        self.btn_encode.setText(_translate("BaseWidget", "编码"))
        self.btn_decode.setText(_translate("BaseWidget", "解码"))
