# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BaseWidget(object):
    def setupUi(self, BaseWidget):
        BaseWidget.setObjectName("BaseWidget")
        BaseWidget.resize(758, 588)
        BaseWidget.setMinimumSize(QtCore.QSize(90, 40))
        self.verticalLayout = QtWidgets.QVBoxLayout(BaseWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(BaseWidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 320))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_left = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_left.setMinimumSize(QtCore.QSize(0, 300))
        self.txt_left.setMaximumSize(QtCore.QSize(16777215, 300))
        self.txt_left.setPlainText("")
        self.txt_left.setObjectName("txt_left")
        self.horizontalLayout.addWidget(self.txt_left)
        self.txt_right = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_right.setMinimumSize(QtCore.QSize(0, 300))
        self.txt_right.setMaximumSize(QtCore.QSize(16777215, 300))
        self.txt_right.setReadOnly(True)
        self.txt_right.setObjectName("txt_right")
        self.horizontalLayout.addWidget(self.txt_right)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(BaseWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(1111111, 58))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_encode = QtWidgets.QPushButton(self.widget_2)
        self.btn_encode.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_encode.setMaximumSize(QtCore.QSize(90, 40))
        self.btn_encode.setObjectName("btn_encode")
        self.horizontalLayout_2.addWidget(self.btn_encode)
        self.btn_decode = QtWidgets.QPushButton(self.widget_2)
        self.btn_decode.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_decode.setMaximumSize(QtCore.QSize(90, 40))
        self.btn_decode.setObjectName("btn_decode")
        self.horizontalLayout_2.addWidget(self.btn_decode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(BaseWidget)
        QtCore.QMetaObject.connectSlotsByName(BaseWidget)

    def retranslateUi(self, BaseWidget):
        _translate = QtCore.QCoreApplication.translate
        BaseWidget.setWindowTitle(_translate("BaseWidget", "Form"))
        self.btn_encode.setText(_translate("BaseWidget", "编码"))
        self.btn_decode.setText(_translate("BaseWidget", "解码"))
